baseURL = "https://water-gis.com"
languageCode = "en-us"

title = "GIS for Water"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/watergis/docs/edit/master/content/"
  description = "Documentation of GIS for Water"
  author = "Jin IGARASHI"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation of GIS for Water"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
url = "https://github.com/watergis/docs"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "/showcase"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-tools'></i> Third party tools"
url = "/tools"
weight = 21


[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-question'></i> Q&A"
url = "/questions"
weight = 22

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-address-card'></i> Contacts"
identifier = "ds"
url = "https://jin-igarashi.me/en"
weight = 40

[Languages.ja]
title = "GIS for Waterドキュメンテーション"
weight = 2
languageName = "日本語"

[[Languages.ja.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHubリポジトリ"
url = "https://github.com/watergis/docs"
weight = 10

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> ショーケース"
url = "/showcase"
weight = 20

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-tools'></i> サードパーティのツール"
url = "/tools"
weight = 21

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-question'></i> Q&A"
url = "/questions"
weight = 22

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> クレジット"
url = "/credits"
weight = 30

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-address-card'></i> 連絡先"
identifier = "ds"
url = "https://jin-igarashi.me/ja"
weight = 40